### ISSUE TITLE
Watched addresses are not re-subscribed on Blockbook when websocket connection is restarted

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/multiwallet#106]
When the websocket connection from multiwallet to blockbook is restarted by the websocket watchdog, we are not re-subscribing to watched addresses. This causes the multiwallet to ignore new transactions reported by the network for addresses of interest and the internal wallet state cannot be updated until a manual restart of the multiwallet is triggered.

Acceptance criteria for a fix:
- [x] Ensure the current list of watched addresses are available from a canonical interface. (I believe the most likely source would be https://github.com/OpenBazaar/openbazaar-go/blob/f3499105bfdb834cddf365e140f391ffac0033f8/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go#L569, but that needs to be verified.)
- [x] Trigger re-subscription of all watched addresses _from their canonical source_ similar to as-shown in https://github.com/OpenBazaar/openbazaar-go/blob/f3499105bfdb834cddf365e140f391ffac0033f8/vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go#L620-L626.
- [x] Bonus: The re-subscription should be batched into a single websocket `subscribe`.
- [ ] ~Bonus: Refactor other cases where this subscription occurs to reuse this behavior.~ Not needed.

**Comment by hoffmabc** [comment]
https://github.com/OpenBazaar/openbazaar-go/issues/1919 tracks the multiwallet AddWatchedAddresses optimization @placer14 .

**Comment by hoffmabc** [comment]
This does in fact seem to be the authoritative source when spinning up the node https://github.com/OpenBazaar/openbazaar-go/blob/f3499105bfdb834cddf365e140f391ffac0033f8/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go#L569

**Comment by hoffmabc** [comment]
It seems as though addresses are re-subscribed in the code already on socket disconnection @placer14. I'm confused.

On disconnect we bark the watchdog

```
i.SocketClient.On(gosocketio.OnDisconnection, func(c *gosocketio.Channel) {
		Log.Warningf("websocket disconnected (%s)", i.String())
		i.websocketWatchdog.bark()
	})
```

which triggers a `setupListeners()` call that reconnects the subscription.

```
func (w *wsWatchdog) guardWebsocket() {
	var t = time.NewTicker(1 * time.Second)
	defer t.Stop()
	for range t.C {
		select {
		case <-w.wsStopped:
			Log.Warningf("reconnecting stopped websocket (%s)", w.client.String())
			w.client.socketMutex.Lock()
			if w.client.SocketClient != nil {
				w.client.SocketClient.Close()
				w.client.SocketClient = nil
			}
			w.drainAndRollover()
			if err := w.client.setupListeners(); err != nil {
				Log.Warningf("failed reconnecting websocket (%s)", w.client.String())
				w.client.socketMutex.Unlock()
				w.client.sendAndDiscardCloseChan(fmt.Errorf("websocket unavailable (%s): %s", w.client.String(), err.Error()))
				go w.putAway()
				return
			}
			w.client.socketMutex.Unlock()
		case <-w.done:
			return
		}
	}
}
```

`setupListeners()` executes:

```
for _, addr := range i.listenQueue {
		var args []interface{}
		args = append(args, "bitcoind/addresstxid")
		args = append(args, []string{addr})
		i.SocketClient.Emit("subscribe", args)
	}
```

which subscribes to those in the listenQueue again.

**Comment by hoffmabc** [comment]
I can make this subscribe obviously a bulk one but that doesn't change the reconnect behavior.

**Comment by placer14** [comment]
Closing as resolved by https://github.com/OpenBazaar/openbazaar-go/issues/1918.
