### ISSUE TITLE
How to install Multiwallet and use

### ISSUE THREAD

**Issue by HafeezRai** [OpenBazaar/multiwallet#44]
Hi i am new to golang can any one provide me steps to run this.
Can i access it through rpc or rest api?

**Comment by placer14** [comment]
@HafeezRai at the moment, multiwallet RPC is not functioning. There are a few commands you can run, but you'll need to setup your go environment to build it first. You can follow these instructions first to setup go: https://golang.org/doc/install

Then, you should be able execute the following commands:

```
go get -u github.com/OpenBazaar/multiwallet
cd $GOPATH/src/github.com/OpenBazaar/multiwallet

go run cmd/multiwallet/main.go -h
```

That last command will give you some subcommands you can then add to the end (in place of the `-h`):
```
Usage:
  main [OPTIONS] <command>

Help Options:
  -h, --help  Show this help message

Available commands:
  balance         get the wallet's balances
  chaintip        return the height of the chain
  currentaddress  get the current bitcoin address
  dumptables      print out the database tables
  newaddress      get a new bitcoin address
  spend           send bitcoins
  start           start the wallet
  stop            stop the wallet
  version         print the version number
```

**Comment by 9z25** [comment]
@placer14 When I try following your directions, errors are thrown for Mocktxnstore. It all looks like simple type errors. Is there anyway around this?
